### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/snooze#2]
Hi Joao, after some cursory reading about snooze.
- There `started-p` and `resource-p` don't follow convention. It is bad enough that CL has the archaic p/-p convention instead of ? to pile on irregularity. single words have no hyphen, otherwise -p at the end. I'm guessing you are aware of the convention but have some objection to it?
- There is no patch http is missing
- breaking up common.lisp in files instead of sections with delimited ^L would make code more approachable for new comers. This is not an issue yet for snooze but can become an issue as the codebase grows like in swank.

**Comment by capitaomorte** [comment]
>  I'm guessing you are aware of the convention but have some objection to it?

I am aware of it, but I stick to `-p`. I do follow the `defthingy` `define-new-thingy` convention, cause that doesn't hamper legibility as much.

> There is no patch http is missing

patches welcome! pun intended. 

> breaking up common.lisp in files instead of sections with delimited ^L would make code more approachable for new comers.

Yes. Also remembering why I came up with common.lisp and the `snooze-common` package might help :-). What was I thinking, what the heck is it "common" with?

**Comment by capitaomorte** [comment]
> I am aware of it, but I stick to -p. I do follow the defthingy define-new-thingy convention, cause that doesn't hamper legibility as much.

I just notice that I _do_ follow it in some places like `stringp` and `errorp`... so much for coherence. Well let me try to come up with something not totally ad-hoc at all... Let's say I follow it when the (short) word is a CL concept, and not something from my problem domain. So `integerp`, `conditionp` but `frobnicator-p`.

**Comment by PuercoPop** [comment]
Why go halfway causing confusion on newcomers and oldtimers a like? Why not just use ? for predicates like the scheemers.

Also ensure-uri could be replaced with (yuri)[https://github.com/TBRSS/yuri]

**Comment by mdbergmann** [comment]
> It is bad enough that CL has the archaic p/-p convention instead of ? to pile on irregularity.

What a nonsense.
p/-p is Common Lisp. ? is Scheme.

**Comment by joaotavora** [comment]
Since I had this discussion, I was pointed to this relevant section of CLtL2:

https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node69.html

**Comment by joaotavora** [comment]
Also, I think this issue can be closed.  But discussion can continue, of course.

**Comment by mdbergmann** [comment]
Sure, close it.
