### ISSUE TITLE
Case sensitive path

### ISSUE THREAD

**Issue by n00p3** [joaotavora/snooze#30]
Consider following snippet:
```common-lisp
(defroute test (:get :text/* path) (format nil "~a" (type-of path)))
```
When I request `localhost:9004/test/123`, then `path` is an integer, but if I request `localhost:9004/test/abc`, then path is a symbol. Is it possible to get string/pipe delimited symbol instead of just regular symbol? I need to have preserved information about character case.

**Comment by joaotavora** [comment]
Maybe this helps: https://github.com/joaotavora/snooze#how-snooze-converts-uri-components-to-arguments

**Comment by n00p3** [comment]
Ok, solved it by adding 
```common-lisp
(defmethod snooze:read-for-resource ((resource (eql #'test)) string)
	   string)
```

**Comment by joaotavora** [comment]
If you want to do that, you should also probably write a `snooze:write-for-resource` so that you can use the `defgenpath` helper and generate URLs for you routes.
