### ISSUE TITLE
Following readme, /lispdoc/funny-syntax?package=snooze generates 400 error, not 404

### ISSUE THREAD

**Issue by sabracrolleton** [joaotavora/snooze#4]
If I am following the readme correctly, then 

http://localhost:9003/lispdoc/defun 

generates "Define a function at top level." which looks correct, but 

http://localhost:9003/lispdoc/funny-syntax?package=snooze

generates a 400 error

as does 

http://localhost:9003/lispdoc/start?package=snooze

Did something change or am I missing something?

**Comment by joaotavora** [comment]
> Did something change?

Yes something dig, i introduced a bug in b1300ea2cec04bcd9372cee55a941486ff444217, should be fixed now.

**Comment by sabracrolleton** [comment]
Is fixed. Thank you.
