### ISSUE TITLE
Snooze Roadmap

### ISSUE THREAD

**Issue by azzamsa** [joaotavora/snooze#7]
Hi, Távora.
Thanks lot for your contribution to community.

Sorry for asking, Is Snooze has roadmap or something like todo list. ?

Thank you.

*I hope the beta status will dissapear soon :)*

**Comment by joaotavora** [comment]
No, no roadmap. I use ir for myself and i think someone else also picked it
up recently. So why don't you propose a roadmap? :)

**Comment by azzamsa** [comment]
> So why don't you propose a roadmap? :)

You are really amazing, happy to meet you.

Okay, I want to try Snooze at this long holiday. 
Sly and Yas are great, so Snooze deserved a try. You also make someone pretty happy with Snooze out there, he told me to give it a try :)

I am new to web development, so I think I can't analyze what feature should be added to snooze.

Last, thank you so much for all your contribution to community, really thanks.
Hope you are always healthy.

**Comment by joaotavora** [comment]
Thanks, likewise, and a happy 2018,

**Comment by priyadarshan** [comment]
BTW, Snooze was mentioned here: https://www.reddit.com/r/Common_Lisp/comments/7mkz3b/advice_for_startup_using_common_lisp/druyxd8/

**Comment by azzamsa** [comment]
@priyadarshan Yes, That was Vindarel, he told me about snooze long before I ask that question.
